[test] update test queries
sebastianrcnt/earglass pull request #5
Opened 2020-10-28 18:44 UTC by 2hwayoung

2020-10-29 10:52 UTC, sebastianrcnt requested changes
- 테스팅 할 수 있는 코드들을 만들어놓은거지? 좋은 것 같아!
- 서버에서 한글 폴더명( 참고자료/ )은 혹시 인코딩 문제가 있을 수 있을 것 같아서 적합한 영어 이름으로 바꿔줬으면 좋겠어!

2020-10-29 10:52 UTC, sebastianrcnt commented on query/create_table.sql
> +  `TypeName` VARCHAR(45) NOT NULL,
UpperCamelCase로 바꾼거지? 굳굳!!

2020-10-29 11:24 UTC, 2hwayoung commented on query/create_table.sql
> +  `TypeName` VARCHAR(45) NOT NULL,
넹^0^ 바꿔놓을께~~

2020-10-29 21:18 UTC, 2hwayoung commented
1. table schema 수정
2. 테이블 생성 query문 수정
3. sample data insert (folder : insertTableData & originDSF)

2020-10-30 08:29 UTC, sebastianrcnt approved these changes
👍🏻

2020-10-30 08:29 UTC, merged